spring:
  datasource:
      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://db:5432/postgres?useSSL=false
      url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
      username: postgres
      password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format_sql: TRUE
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
#  sql:
#      init:
#        mode: always
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor: TRACE
    blog: DEBUG
    root: debug
server:
  error:
    whitelabel:
      enabled: false
    path: /error
